create
or replace view STOCK_ANALYTICS.PUBLIC.MODEL_DATA(
    QUARTER_END,
    SYMBOL,
    DATE,
    OPEN,
    HIGH,
    LOW,
    CLOSE,
    ADJCLOSE,
    VOLUME,
    UNADJUSTEDVOLUME,
    CHANGE,
    CHANGEPERCENT,
    VWAP,
    CHANGEOVERTIME,
    SMA_5D,
    SMA_10D,
    SMA_15D,
    SMA_20D,
    EMA_5D,
    EMA_10D,
    EMA_15D,
    EMA_20D,
    WMA_5D,
    WMA_10D,
    WMA_15D,
    WMA_20D,
    DEMA_5D,
    DEMA_10D,
    DEMA_15D,
    DEMA_20D,
    TEMA_5D,
    TEMA_10D,
    TEMA_15D,
    TEMA_20D,
    WILLIAMS_5D,
    WILLIAMS_10D,
    WILLIAMS_15D,
    WILLIAMS_20D,
    RSI_5D,
    RSI_10D,
    RSI_15D,
    RSI_20D,
    ADX_5D,
    ADX_10D,
    ADX_15D,
    ADX_20D,
    STANDARDDEVIATION_5D,
    STANDARDDEVIATION_10D,
    STANDARDDEVIATION_15D,
    STANDARDDEVIATION_20D,
    MONTHLY_RETURN_PERC,
    CURRENTRATIO,
    QUICKRATIO,
    CASHRATIO,
    DAYSOFSALESOUTSTANDING,
    DAYSOFINVENTORYOUTSTANDING,
    OPERATINGCYCLE,
    DAYSOFPAYABLESOUTSTANDING,
    CASHCONVERSIONCYCLE,
    GROSSPROFITMARGIN,
    OPERATINGPROFITMARGIN,
    PRETAXPROFITMARGIN,
    NETPROFITMARGIN,
    EFFECTIVETAXRATE,
    RETURNONASSETS,
    RETURNONEQUITY,
    RETURNONCAPITALEMPLOYED,
    NETINCOMEPEREBT,
    EBTPEREBIT,
    EBITPERREVENUE,
    DEBTRATIO,
    DEBTEQUITYRATIO,
    LONGTERMDEBTTOCAPITALIZATION,
    TOTALDEBTTOCAPITALIZATION,
    INTERESTCOVERAGE,
    CASHFLOWTODEBTRATIO,
    COMPANYEQUITYMULTIPLIER,
    RECEIVABLESTURNOVER,
    PAYABLESTURNOVER,
    INVENTORYTURNOVER,
    FIXEDASSETTURNOVER,
    ASSETTURNOVER,
    OPERATINGCASHFLOWPERSHARE,
    FREECASHFLOWPERSHARE,
    CASHPERSHARE,
    PAYOUTRATIO,
    OPERATINGCASHFLOWSALESRATIO,
    FREECASHFLOWOPERATINGCASHFLOWRATIO,
    CASHFLOWCOVERAGERATIOS,
    SHORTTERMCOVERAGERATIOS,
    CAPITALEXPENDITURECOVERAGERATIO,
    DIVIDENDPAIDANDCAPEXCOVERAGERATIO,
    DIVIDENDPAYOUTRATIO,
    PRICEBOOKVALUERATIO,
    PRICETOBOOKRATIO,
    PRICETOSALESRATIO,
    PRICEEARNINGSRATIO,
    PRICETOFREECASHFLOWSRATIO,
    PRICETOOPERATINGCASHFLOWSRATIO,
    PRICECASHFLOWRATIO,
    PRICEEARNINGSTOGROWTHRATIO,
    PRICESALESRATIO,
    DIVIDENDYIELD,
    ENTERPRISEVALUEMULTIPLE,
    PRICEFAIRVALUE,
    TARGET
) as (
    WITH MONTHLY_OHLC_TECH_IND_6Y_CTE AS (
        SELECT
            DATEADD(
                DAY,
                -1,
                DATEADD(
                    QUARTER,
                    1,
                    DATE_TRUNC('QUARTER', DATEADD(DAY, -5, DATE))
                )
            ) AS QUARTER_END,
            *
        FROM
            MONTHLY_OHLC_TECH_IND_6Y
    ),
    FINANCIAL_RATIOS_CTE AS(
        SELECT
            DATEADD(
                DAY,
                -1,
                DATEADD(
                    QUARTER,
                    1,
                    DATE_TRUNC('QUARTER', DATEADD(DAY, -5, DATE))
                )
            ) AS QUARTER_END,
            *
        FROM
            FINANCIAL_RATIOS
        ORDER BY
            SYMBOL,
            DATE DESC
    )
    SELECT
        OHLC.* EXCLUDE TARGET,
        FR.* EXCLUDE (
            QUARTER_END,
            DATE,
            SYMBOL,
            CALENDARYEAR,
            PERIOD,
            SNAPSHOT_DATE
        ),
        OHLC.TARGET
    FROM
        MONTHLY_OHLC_TECH_IND_6Y_CTE OHLC
        LEFT JOIN FINANCIAL_RATIOS_CTE FR ON FR.QUARTER_END = OHLC.QUARTER_END
        AND OHLC.SYMBOL = FR.SYMBOL
    WHERE
        FR.DATE IS NOT NULL
);